In [ ]:
%%capture
!pip install jax jaxlib flax optax mtranslate sentencepiece datasets transformers accelerate scikit-learn ipywidgets datasets nltk importlib-metadata
!pip install transformers --upgrade

from IPython.display import display, HTML
# from huggingface_hub import notebook_login
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import json
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoConfig, AutoModelForQuestionAnswering, AdamW, Trainer, TrainingArguments, default_data_collator, FlaxAutoModelForQuestionAnswering
import time
import nltk
import math
import torch
from datasets import Dataset, DatasetDict, load_dataset, load_metric
import tensorflow as tf
import re
from torch.nn.utils.rnn import pad_sequence
from tensorflow import keras
from tensorflow.keras import layers
import torch
import torch.nn as nn
import torch.optim as optim
import transformers
# from accelerate import Accelerator
import datasets
import sentencepiece
from time import sleep
from time import time
from random import randint


In [33]:
# Вход в huggingface
# notebook_login()
!huggingface-cli login --token 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

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid.
Your token has been saved to /root/.cache/huggingface/token
Login successful


# EDA

In [ ]:
from transformers import FlaxMarianMTModel, AutoTokenizer
import jax
from jax import vmap
import jax.numpy as jnp
import jax.numpy as jnp
import jax.lax as lax
# from tqdm import tqdm

In [ ]:

# загружаем данные для обучения
with open('/kaggle/input/nlp-test-task-2023/nlp_test_task_2023/dataset/train.json', 'r', encoding='utf-8') as file:
    train_data = json.load(file)

# загружаем данные для предсказания
with open('/kaggle/input/nlp-test-task-2023/nlp_test_task_2023/dataset/test.json', 'r', encoding='utf-8') as file:
    test_data = json.load(file)

# Разбиваем данные на обучающую и валидационную выборки
train_data, val_data = train_test_split(train_data, test_size=0.2, random_state=42)

def clean_text(text):
    # Удаление указанных символов из текста
    text = re.sub(r'[\"\#\$\;\:\^\&\№\*\-\=\+\-\,\.\@\!\?\/\]\[\}\{\|\~\«\»\`]', '', text)
    text = re.sub(r'_', ' ', text)  # Замена _ на пробел
    text = re.sub(r'\s+', ' ', text)  # Удаление лишних пробелов
    return text.strip()

def create_qa_dataframe(data):
    examples = []
    for row in tqdm(data, total = len(data)):
        cleaned_text = clean_text(row['text'])
        question = row['label']
        extracted_part = row.get('extracted_part', {})
        if extracted_part and extracted_part['text'] is not None:
            answer = clean_text(extracted_part['text'][0].strip())
            answer_start = extracted_part['answer_start'][0]
            answer_end = extracted_part['answer_end'][0]
            if answer:
                answer_words = answer.split()
                match_found = False
                for i in range(len(answer_words)):
                    answer_start_new = cleaned_text.find(answer_words[i])
                    if answer_start_new != -1:
                        match_found = True
                        for j in range(i+1, len(answer_words)):
                            next_word_start = answer_start_new + len(answer_words[i-1])
                            next_word_end = next_word_start + len(answer_words[j])
                            next_word = cleaned_text[next_word_start:next_word_end]
                            if answer_words[j] != next_word:
                                match_found = False
                                break
                        if match_found:
                            answer_start = answer_start_new
                            answer_end = answer_start_new + len(answer_words) - 1
                            break
                if not match_found:
                    answer_start = answer_end = 0
            else:
                answer_start = answer_end = 0
        else:
            answer_start = answer_end = 0
            answer = None
            
#         translated_text = translate_sentence(cleaned_text)
#         translated_question = translate_sentence(question)
#         translated_answer = translate_sentence(answer) if answer else None

        example = {'context': cleaned_text, 'question': question, 'answer': answer, 'answer_start': answer_start, 'answer_end': answer_end}
        examples.append(example)
    df = pd.DataFrame(examples)
    return df

In [ ]:
train_df = create_qa_dataframe(train_data)
display(HTML(train_df[6:12].to_html()))

# Create dataset

In [40]:
# import mtranslate

class QADataset:
    def __init__(self, train_data, val_data, test_data=None, zero_flag=False):
        self.zero_flag = zero_flag
        self.train_examples = self.create_qa_example(train_data)
        self.val_examples = self.create_qa_example(val_data)
        self.test_examples = self.create_qa_example(test_data) if test_data else []
        self.train_dataset = datasets.Dataset.from_pandas(pd.DataFrame(self.train_examples))
        self.val_dataset = datasets.Dataset.from_pandas(pd.DataFrame(self.val_examples))
        self.test_dataset = datasets.Dataset.from_pandas(pd.DataFrame(self.test_examples)) if test_data else None
        if test_data:
            self.dataset_dict = DatasetDict({
                'train': self.train_dataset,
                'validation': self.val_dataset,
                'test': self.test_dataset
            })
        else:
            self.dataset_dict = DatasetDict({
                'train': self.train_dataset,
                'validation': self.val_dataset
            })

    def clean_text(self, text):
        # Удаление указанных символов из текста
        text = re.sub(r'[\"\#\$\;\:\^\&\№\*\-\=\+\-\,\.\@\!\?\/\]\[\}\{\|\~\«\»\`]', '', text)
        text = re.sub(r'_', ' ', text)  # Замена _ на пробел
        text = re.sub(r'\s+', ' ', text)  # Удаление лишних пробелов
        return text.strip()

    def create_qa_example(self, data):
        examples = []
        for row in tqdm(data, total = len(data)):
            cleaned_text = self.clean_text(row['text'])
            question = row['label']
            extracted_part = row.get('extracted_part', {})
            if extracted_part and extracted_part['text'] is not None:
                answer = self.clean_text(extracted_part['text'][0].strip())
                answer_start = extracted_part['answer_start'][0]
                answer_end = extracted_part['answer_end'][0]
                if answer:
                    answer_words = answer.split()
                    match_found = False
                    for i in range(len(answer_words)):
                        answer_start_new = cleaned_text.find(answer_words[i])
                        if answer_start_new != -1:
                            match_found = True
                            for j in range(i+1, len(answer_words)):
                                next_word_start = answer_start_new + len(answer_words[i-1])
                                next_word_end = next_word_start + len(answer_words[j])
                                next_word = cleaned_text[next_word_start:next_word_end]
                                if answer_words[j] != next_word:
                                    match_found = False
                                    break
                            if match_found:
                                answer_start = answer_start_new
                                answer_end = answer_start_new + len(answer_words) - 1
                                break
                    if not match_found:
                        answer_start = answer_end = 0
                else:
                    answer_start = answer_end = 0
            else:
                answer_start = answer_end = 0
                answer = None

#             translated_text = translate_sentence(cleaned_text)
    #         translated_question = translate_sentence(question)
    #         translated_answer = translate_sentence(answer) if answer else None

            # Append example only if answer is not None
            if self.zero_flag:
                if answer_start != 0 :
                    example = {'context': cleaned_text, 'question': question, 'answer': answer, 'answer_start': answer_start, 'answer_end': answer_end}
                    examples.append(example)
            else:
                example = {'context': cleaned_text, 'question': question, 'answer': answer, 'answer_start': answer_start, 'answer_end': answer_end}
                examples.append(example)
            
        return examples
    
def prepare_train_features(examples):
#     examples["question"] = [q.lstrip() for q in examples["question"]]
    tokenized_examples = tokenizer(
        examples["question"],
        examples["context"],
        truncation="only_second",
        max_length=max_length,
        stride=150,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
        return_tensors="jax",
    )
    sample_mapping = tokenized_examples.pop("overflow_to_sample_mapping")
    offset_mapping = tokenized_examples.pop("offset_mapping")
    tokenized_examples["start_positions"] = []
    tokenized_examples["end_positions"] = []

    for i, offsets in enumerate(offset_mapping):
        input_ids = tokenized_examples["input_ids"][i]
        mask_indices = np.where(input_ids == 2)[0]
        second_mask_index = mask_indices[-2]+1
#         cls_index = input_ids.index(tokenizer.cls_token_id)
        cls_index = jnp.where(input_ids == tokenizer.cls_token_id)[0][0]
        sequence_ids = tokenized_examples.sequence_ids(i)
        sample_index = sample_mapping[i]
        answer_start = examples["answer_start"][sample_index]
        answer_end = examples["answer_end"][sample_index]
        if answer_start == 0 or answer_start == None:
            tokenized_examples["start_positions"].append(cls_index)
            tokenized_examples["end_positions"].append(cls_index)
        else:
            tokenized_examples["start_positions"].append(answer_start+second_mask_index)
            tokenized_examples["end_positions"].append(answer_end+second_mask_index)

    return tokenized_examples

# Used git finetune script

In [2]:
model_name = 'xlm-roberta-base'
max_length = 1440
tokenizer = AutoTokenizer.from_pretrained(model_name)
config = AutoConfig.from_pretrained(model_name)
model = FlaxAutoModelForQuestionAnswering.from_pretrained(model_name, config=config)

In [31]:
# Пример
context = "УТВЕРЖДАЮ Председатель закупочной комиссии заместитель генерального директора по логистике и МТО АО АТХ ТЮ Шустова 01 сентября 2022 г ДОКУМЕНТАЦИЯ О КОНКУРЕНТНОЙ ЗАКУПКЕ ЗАПРОС ПРЕДЛОЖЕНИЙ В ЭЛЕКТРОННОЙ ФОРМЕ УЧАСТНИКАМИ КОТОРОГО МОГУТ БЫТЬ ТОЛЬКО СУБЪЕКТЫ МАЛОГО И СРЕДНЕГО ПРЕДПРИНИМАТЕЛЬСТВА на право заключения Договора на выполнение работ по ремонту зданий и сооружений г Киров 2022 год Стр2 СОДЕРЖАНИЕ СОДЕРЖАНИЕ 2 I ОБЩИЕ УСЛОВИЯ ПРОВЕДЕНИЯ закупки 3 1 ОБЩИЕ ПОЛОЖЕНИЯ 3 11 Правовой статус документов 3 12 Заказчик предмет и условия проведения закупки 3 13 Начальная (максимальная) цена договора 4 14 Требования к участникам закупки 4 15 Участие в закупке коллективных участников (группы лиц) 5 16 Привлечение соисполнителей (субподрядчиков) к исполнению договора 6 17 Расходы на участие в закупке и при заключении договора 7 18 Предоставление приоритетов товаров российского происхождения работ услуг выполняемых оказываемых российс 352 564 Закупка по единичным расценкам"
question = "обеспечение гарантийных обязательств"

def get_best_indexes(inputs, outputs):
#     mask_indices = np.where(inputs['input_ids'][0] == 2)[0]
#     last_mask_index = mask_indices[-1]-1
#     second_last_mask_index = mask_indices[-2]+1
    start_logits = outputs.start_logits[0]
    end_logits = outputs.end_logits[0]

    # Softmax
    start_probs = np.exp(start_logits) / np.sum(np.exp(start_logits))
    end_probs = np.exp(end_logits) / np.sum(np.exp(end_logits))

    # Поиск индексов с наибольшим произведением вероятностей
    max_prob = 0
    best_pair = None
    for start_idx in range(start_probs.shape[0]):
        for end_idx in range(start_idx, end_probs.shape[0]):
            prob = (start_probs[start_idx] * end_probs[end_idx]).max()
            if prob > max_prob:
                max_prob = prob
                best_pair = (start_idx, end_idx)

    return best_pair[0], best_pair[1]
# 
inputs = tokenizer(question, context, truncation="only_second",
        max_length=max_length,
        padding="max_length",
        return_tensors="jax",)

outputs = model(**inputs)

# start_logits = outputs.start_logits[0][len(tokenizer.encode(question))+1:(len(tokenizer.encode(question))+1)+(len(tokenizer.encode(context)))-2]
# end_logits = outputs.end_logits[0][len(tokenizer.encode(question))+1:(len(tokenizer.encode(question))+1)+(len(tokenizer.encode(context)))-2]

# start_logits = outputs.start_logits[0]
# end_logits = outputs.end_logits[0]
# start_probs = jax.nn.softmax(start_logits, axis=-1)
# end_probs = jax.nn.softmax(end_logits, axis=-1)
# max_prob = 0
# best_pair = None
# for start_idx in range(start_probs.shape[0]):
#     for end_idx in range(start_idx, end_probs.shape[0]):
#         prob = (start_probs[start_idx] * end_probs[end_idx]).max()
#         if prob > max_prob:
#             max_prob = prob
#             best_pair = (start_idx, end_idx)
# tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0][len(tokenizer.encode(question))+1:(len(tokenizer.encode(question))+1)+(len(tokenizer.encode(context)))-2])
best_start, best_end = get_best_indexes(inputs, outputs)
tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
answer_tokens = tokens[best_start:best_end]
answer = tokenizer.convert_tokens_to_string(answer_tokens)
print(answer)

ЪЕКТЫ МАЛОГО И СРЕДНЕГО ПРЕДПРИНИМАТЕЛЬСТВА на право заключения Договора на выполнение работ по ремонту зданий и сооружений г Киров 2022 год Стр2 СОДЕРЖАНИЕ СОДЕРЖАНИЕ 2 I ОБЩИЕ УСЛОВИЯ ПРОВЕДЕНИЯ закупки 3 1 ОБЩИЕ ПОЛОЖЕНИЯ


DeviceArray(123090, dtype=int32)

# TPU used try 1

In [35]:
import jax
import flax
import optax
from itertools import chain
from typing import Callable
import jax.numpy as jnp
from flax.training.common_utils import get_metrics, onehot, shard, shard_prng_key
from flax.training import train_state
from flax import traverse_util
# from torch.utils.data import DataLoader
# import datasets

In [ ]:
print(flax.__version__)
jax.local_devices()

In [39]:
from tqdm import tqdm

# загружаем данные для обучения
with open('/kaggle/input/nlp-test-task-2023/nlp_test_task_2023/dataset/train.json', 'r', encoding='utf-8') as file:
    train_data = json.load(file)

# загружаем данные для предсказания
with open('/kaggle/input/nlp-test-task-2023/nlp_test_task_2023/dataset/test.json', 'r', encoding='utf-8') as file:
    test_data = json.load(file)

# Разбиваем данные на обучающую и валидационную выборки
train_data, val_data = train_test_split(train_data, test_size=0.2, random_state=42)

# Args
num_labels = 1
seed = 60
num_train_epochs = 8
learning_rate = 2e-5
per_device_batch_size = 1
total_batch_size = per_device_batch_size * jax.local_device_count()
model_name = 'xlm-roberta-base'
# "distilbert-base-uncased"
max_length = 832

# model elements
tokenizer = AutoTokenizer.from_pretrained(model_name)
config = AutoConfig.from_pretrained(model_name)
model = FlaxAutoModelForQuestionAnswering.from_pretrained(model_name, config=config)
pad_on_right = tokenizer.padding_side == "right"

# dataset
qa_dataset = QADataset(train_data, val_data, test_data=test_data)
# test_data=test_data
tokenized_dataset = qa_dataset.dataset_dict.map(prepare_train_features, batched=True, 
                                                 remove_columns=qa_dataset.dataset_dict["train"].column_names)
train_dataset = tokenized_dataset["train"]
eval_dataset = tokenized_dataset["validation"]
test_dataset = tokenized_dataset["test"]

#add args
num_train_steps = len(train_dataset) // total_batch_size * num_train_epochs

print("The overall batch size (both for training and eval) is", total_batch_size)
print("The number of train steps (all the epochs) is", num_train_steps)

100%|██████████| 318/318 [00:00<00:00, 5152.79it/s]


  0%|          | 0/2 [00:00<?, ?ba/s]

[  6   7 290]
8
[  6   7 314]
8
[  6   7 297]
8
[  5   6 457]
7
[  6   7 278]
8
[  5   6 519]
7
[  6   7 506]
8
[  5   6 511]
7
[  5   6 479]
7
[  5   6 521]
7
[  6   7 226]
8
[  6   7 419]
8
[  5   6 508]
7
[  5   6 466]
7
[  5   6 499]
7
[  6   7 323]
8
[  6   7 497]
8
[  5   6 497]
7
[  5   6 481]
7
[  6   7 463]
8
[  5   6 483]
7
[  5   6 555]
7
[  5   6 532]
7
[  5   6 483]
7
[  5   6 510]
7
[  6   7 547]
8
[  5   6 487]
7
[  5   6 546]
7
[  6   7 572]
8
[  5   6 465]
7
[  5   6 532]
7
[  6   7 193]
8
[  5   6 492]
7
[  6   7 291]
8
[  5   6 493]
7
[  6   7 538]
8
[  6   7 325]
8
[  5   6 499]
7
[  5   6 443]
7
[  5   6 475]
7
[  5   6 535]
7
[  5   6 510]
7
[  5   6 545]
7
[  5   6 519]
7
[  5   6 522]
7
[  6   7 420]
8
[  5   6 516]
7
[  5   6 509]
7
[  5   6 510]
7
[  6   7 598]
8
[  6   7 330]
8
[  6   7 206]
8
[  5   6 502]
7
[  6   7 522]
8
[  5   6 454]
7
[  5   6 536]
7
[  5   6 552]
7
[  6   7 261]
8
[  6   7 530]
8
[  5   6 529]
7
[  5   6 517]
7
[  5   6 465]
7
[  5   6

TypeError: Provided `function` which is applied to all elements of table returns a `dict` of types [<class 'jaxlib.xla_extension.DeviceArray'>, <class 'jaxlib.xla_extension.DeviceArray'>, <class 'list'>, <class 'list'>]. When using `batched=True`, make sure provided `function` returns a `dict` of types like `(<class 'list'>, <class 'numpy.ndarray'>)`.

In [ ]:
tokenized_dataset

In [ ]:
tokenized_dataset['train']['start_positions'][6]

In [ ]:
print(tokenized_dataset['train']['input_ids'][0])

In [ ]:
tokenizer.decode(tokenized_dataset['train']['input_ids'][0])

In [ ]:
# model = FlaxAutoModelForQuestionAnswering.from_pretrained(model_name, config=config)

In [ ]:
# from tqdm import tqdm

class RMSE(datasets.Metric):
    def _info(self):
        return datasets.MetricInfo(
            description="Calculates Root Mean Squared Error (RMSE) metric.",
            citation="TODO: _CITATION",
            inputs_description="_KWARGS_DESCRIPTION",
            features=datasets.Features({
                'predictions': datasets.Value('float32'),
                'references': datasets.Value('float32'),
            }),
            codebase_urls=[],
            reference_urls=[],
            format='numpy'
        )

    def _compute(self, predictions, references):
        rmse = np.sqrt(np.sum(np.square(predictions - references)) / predictions.shape[0])
        return {"RMSE": rmse}

class TrainState(train_state.TrainState):
    logits_function: Callable = flax.struct.field(pytree_node=False)
    loss_function: Callable = flax.struct.field(pytree_node=False)

learning_rate_function = optax.cosine_onecycle_schedule(transition_steps=num_train_steps, 
                                                        peak_value=learning_rate, pct_start=0.1, 
                                                       )
def decay_mask_fn(params):
    flat_params = traverse_util.flatten_dict(params)
    flat_mask = {path: (path[-1] != "bias" and path[-2:] != ("LayerNorm", "scale")) for path in flat_params}
    return traverse_util.unflatten_dict(flat_mask)

# def adamw(weight_decay):
#     return optax.adamw(learning_rate=learning_rate_function, b1=0.9, b2=0.999, eps=1e-6, weight_decay=weight_decay, mask=decay_mask_fn)

# adamw = adamw(1e-2)

def adamw(weight_decay, schedule_fn):
    return optax.chain(
        optax.scale_by_adam(b1=0.9, b2=0.999, eps=1e-6),
        optax.scale_by_schedule(schedule_fn),
        optax.scale(-1.0),
        optax.additive_weight_decay(weight_decay, mask=decay_mask_fn)
    )

def learning_rate_schedule(max_lr, warmup_steps, total_steps):
    step_fn = lambda step: np.minimum((step + 1) / warmup_steps, 1.0)
    lr_fn = lambda step: max_lr * step_fn(step) * (total_steps - step) / np.maximum(total_steps - warmup_steps, 1.0)
    return lr_fn

learning_rate_fn = learning_rate_schedule(max_lr=1e-3, warmup_steps=(num_train_steps/10), total_steps=num_train_steps)
adamw = adamw(weight_decay=1e-2, schedule_fn=learning_rate_fn)

# @jax.jit
# def loss_function(logits, labels):
#     return jnp.mean((logits[..., 0] - labels) ** 2)

@jax.jit
def loss_function(predicted_positions, positions):
#     logits = logits[..., 0] # получение массива start_logits
#     predicted_positions = jnp.argmax(logits, axis=-1) # получение индекса с наибольшим значением в каждом батче
    loss = jnp.mean((predicted_positions - positions) ** 2) # вычисление средней ошибки
    return loss


# @jax.jit    
# def eval_function(logits):
#     return logits[..., 0]

@jax.jit    
def eval_function(logits):
#     logits = logits[..., 0]
#     l_index = jnp.argmax(logits, axis=-1)
#     start_values = jnp.take_along_axis(logits, axis=-1)
    return logits

@jax.jit
def get_best_indexes(outputs):
    
#     mask_indices = jnp.where(batch['input_ids'][0] == 2)[0] # 2 - разделитель </sep>
#     last_mask_index = mask_indices[-1]-1
#     second_last_mask_index = mask_indices[-2]+1
#     start_logits = outputs.start_logits[0][second_last_mask_index:last_mask_index]
#     end_logits = outputs.end_logits[0][second_last_mask_index:last_mask_index]

    end_logits = outputs.end_logits[0]
    start_logits = outputs.start_logits[0]
    
    # Softmax
    start_probs = jax.nn.softmax(start_logits, axis=-1)
    end_probs = jax.nn.softmax(end_logits, axis=-1)

    # Поиск индексов с наибольшим произведением вероятностей
    max_prob = 0
    best_pair = None
    for start_idx in range(start_probs.shape[0]):
        for end_idx in range(start_idx, end_probs.shape[0]):
            prob = (start_probs[start_idx] * end_probs[end_idx]).max()
            if prob > max_prob:
                max_prob = prob
                best_pair = (start_idx, end_idx)

    return best_pair[0], best_pair[1]



state = TrainState.create(apply_fn=model.__call__, params=model.params, tx=adamw,
                          logits_function=eval_function, loss_function=loss_function,
                         )



def train_step(state, batch, dropout_rng):
    start_positions = batch.pop("start_positions")
    end_positions = batch.pop("end_positions")
    dropout_rng, new_dropout_rng = jax.random.split(dropout_rng)

    def loss_fn(params):
        outputs = state.apply_fn(**batch, params=params, dropout_rng=dropout_rng, train=True, return_dict=True)
#         mask_indices = jnp.where(batch['input_ids'][0] == 2, batch['input_ids'])[0]
        start_pred, end_pred = get_best_indexes(outputs)
        start_loss = state.loss_function(start_pred, start_positions)
        end_loss = state.loss_function(end_pred, end_positions)
        loss = (start_loss + end_loss) / 2.0
        return loss

    grad_function = jax.value_and_grad(loss_fn)
    loss, grad = grad_function(state.params)
    grad = jax.lax.pmean(grad, "batch")
    new_state = state.apply_gradients(grads=grad)
    new_params = new_state.params
    new_params = jax.tree_map(lambda p, g: p - learning_rate_fn(state.step) * g, new_state.params, grad)
    new_state = new_state.replace(params=new_params)
    metrics = {"loss": loss, "learning_rate": learning_rate_fn(state.step)}
    print(metrics)
    return new_state, metrics, new_dropout_rng

parallel_train_step = jax.pmap(train_step, axis_name="batch", donate_argnums=(0,))

def eval_step(state, batch):
    outputs = state.apply_fn(**batch, params=state.params, train=False)
#     start_logits = outputs.start_logits
#     end_logits = outputs.end_logits
#     start_logits = jax.lax.pmean(state.logits_function(start_logits), "batch")
#     end_logits = jax.lax.pmean(state.logits_function(end_logits), "batch")
    start_pred, end_pred = get_best_indexes(outputs)
    return state.logits_function(start_pred), state.logits_function(end_pred)

parallel_eval_step = jax.pmap(eval_step, axis_name="batch")

def train_data_loader(rng, dataset, batch_size):
    steps_per_epoch = len(dataset) // batch_size
    perms = jax.random.permutation(rng, len(dataset))
    perms = perms[: steps_per_epoch * batch_size]
    perms = perms.reshape((steps_per_epoch, batch_size))
    for perm in perms:
        batch = dataset[perm]
        batch = {k: jnp.array(v) for k, v in batch.items()}
        batch = shard(batch)
        yield batch
        
def eval_data_loader(dataset, batch_size):
    for i in range(len(dataset) // batch_size):
        batch = dataset[i * batch_size : (i + 1) * batch_size]
        batch = {k: jnp.array(v) for k, v in batch.items()}
        batch = shard(batch)
        yield batch
        
state = flax.jax_utils.replicate(state)
rng = jax.random.PRNGKey(seed)
dropout_rngs = jax.random.split(rng, jax.local_device_count())

In [ ]:
from tqdm import tqdm
metric_start = RMSE()
metric_end = RMSE()
    
for i, epoch in enumerate(tqdm(range(1, num_train_epochs + 1), desc=f"Epoch ...", position=0, leave=True)):
    rng, input_rng = jax.random.split(rng)
    
    metric_start = RMSE()
    metric_end = RMSE()
    
    for batch in train_data_loader(input_rng, train_dataset, total_batch_size):
        state, train_metrics, dropout_rngs = parallel_train_step(state, batch, dropout_rngs)

    # evaluate
    for batch in eval_data_loader(eval_dataset, total_batch_size):
        start_positions = batch["start_positions"]
        end_positions = batch["end_positions"]
        inputs = {k: v for k, v in batch.items() if k not in ["start_positions", "end_positions"]}
        start_logits, end_logits = parallel_eval_step(state, inputs)
        predictions_start = start_logits
        predictions_end = end_logits
        references_start = start_positions
        references_end = end_positions
        print(predictions_start)
        print(references_start)
        metric_start.add_batch(predictions=chain(*predictions_start), references=chain(*references_start))
        metric_end.add_batch(predictions=chain(*predictions_end), references=chain(*references_end))

    start_rmse = round(metric_start.compute()['RMSE'], 3)
    end_rmse = round(metric_end.compute()['RMSE'], 3)

    loss = round(flax.jax_utils.unreplicate(train_metrics)['loss'].item(), 3)
    metric_name = "RMSE"
    print(f"{i+1}/{num_train_epochs} | Train loss: {loss} | Eval {metric_name}: start={start_rmse}, end={end_rmse}")


In [ ]:
question, text = "обеспечение гарантийных обязательств", "Приложение 1 к заявке – заказу от 2022г изненно необходимых и важнейших лекарственных препаратов в соответствии с постановлением Правительства Российской Федерации от 30112015г 1289 Об ограничениях и условиях допуска происходящих из иностранных государств лекарственных препаратов включенных в перечень жизненно необходимых и важнейших лекарственных препаратов для целей осуществления закупок для обеспечения государственных и муниципальных нужд Нет 1810 Установление запрета на допуск товаров легкой промышленности происходящих из иностранных государств и (или) услуг по прокату таких товаров в соответствии с постановлением Правительства Российской Федерации от 11082014г 791 Об установлении запрета на допуск товаров легкой промышленности происходящих из иностранных государств и (или) услуг по прокату таких товаров в целях осуществления закупок для обеспечения федеральных нужд нужд субъектов Российской Федерации и муниципальных нужд Нет 19 Размер обеспечения заявки на участие в электронном аукционе нет 20 Размер обеспечения исполнения контракта 5% от цены контракта 21 Обеспечение исполнения контракта путем внесения денежных средств на указанный заказчиком счет Реквизиты счета для предоставления обеспечения исполнения контракта Наименование учреждения Муниципальное общеобразовательное бюджетное учреждение средняя общеобразовательная школа сТемясово муниципального района Баймакский район Республики Башкортостан Юридический адрес 453663 Республика Башкортостан Баймакский район сТемясово улСоветская 20 ИНН 0254005845 КПП 025401001 Рс 40102810045370000067 Казначейский счет 03234643806060000100 Наименование банка Отделение НБ Республика Башкортостан БИК 018073401 лс 20103020420 Получатель Муниципальное общеобразовательное бюджетное учреждение средняя общеобразовательная школа сТемясово муниципального района Баймакский район Республики Башкортостан Факт внесения денежных средств в качестве обеспечения исполнения контракта подтверждается платежным поручением с отметкой банка об оплате Денежные средства возвращаются поставщику с По согласованию с заказчиком поставка дров может быть осуществлена в полном объеме в более ранние сроки Кубм 500"
inputs = tokenizer(question, text, 
                   truncation="only_second",
                   max_length=max_length,
                   stride=150,
                   return_overflowing_tokens=True,
                   return_offsets_mapping=True,
                   padding="max_length",
                   return_tensors="jax",)

outputs = state.apply_fn(**inputs)
start_scores = outputs.start_logits
end_scores = outputs.end_logits
start_scores

In [ ]:
### import os
import jax
from flax.serialization import to_bytes, from_bytes

# Определяем путь к файлу, в который мы хотим сохранить модель.
model_path = 'my_model.jax'

# Получаем параметры модели, которые мы хотим сохранить.
model_params = jax.tree_map(lambda x: x.block_until_ready(), state.params)

# Преобразуем параметры в байтовую строку.
model_bytes = to_bytes(model_params)

# Сохраняем модель в файл.
with open(model_path, 'wb') as f:
    f.write(model_bytes)

In [ ]:
# import jax
# from flax.serialization import from_bytes

# # Определяем путь к файлу, из которого мы хотим загрузить модель.
# model_path = 'my_model.jax'

# # Загружаем модель из файла.
# with open(model_path, 'rb') as f:
#     model_bytes = f.read()

# # Преобразуем байтовую строку в параметры модели.
# model_params = from_bytes(model_bytes)

# # Создаем новый экземпляр модели, используя загруженные параметры.
# model = FlaxAutoModelForQuestionAnswering(**model_params)


In [ ]:
def test_data_loader(dataset, batch_size):
    if len(dataset)<batch_size:
        batch = dataset[:]
        batch = {k: jnp.array(v) for k, v in batch.items()}
        yield batch
    else:
        for i in range(len(dataset) // batch_size):
            batch = dataset[i * batch_size : (i + 1) * batch_size]
            batch = {k: jnp.array(v) for k, v in batch.items()}

            yield batch
        batch = dataset[(i+1) * batch_size:]
        batch = {k: jnp.array(v) for k, v in batch.items()}
        yield batch
        
from flax.jax_utils import unreplicate

unrep_state = unreplicate(state)


def test_step(unrep_state, batch):
    start_logits, end_logits = unrep_state.apply_fn(**batch, params=unrep_state.params, train=False)[0:2]
    return state.logits_function(start_logits), state.logits_function(end_logits)

parallel_test_step = jax.pmap(test_step, axis_name="batch")

def generate_results():
    preds = []
    for batch in test_data_loader(test_dataset, total_batch_size):

        if jax.process_index() == 0:
            inputs = {k: v for k, v in batch.items()}
            start_logits, end_logits = parallel_test_step(state, inputs)
            preds.append((start_logits, end_logits))
    return preds


In [ ]:
preds = generate_results()

In [ ]:
import os

# os.environ["WANDB_MODE"] = "disabled"
from datasets import Dataset, DatasetDict
import datasets
model_name = "valhalla/longformer-base-4096-finetuned-squadv1" "AlexKay/xlm-roberta-large-qa-multilingual-finedtuned-ru"
max_length = 4000
tokenizer = AutoTokenizer.from_pretrained(model_name)
pad_on_right = tokenizer.padding_side == "right"
qa_dataset = QADataset(train_data, val_data)
tokenized_dataset = qa_dataset.dataset_dict.map(prepare_train_features, batched=True, 
                                                 remove_columns=qa_dataset.dataset_dict["train"].column_names)

QAtrainer = QATrainer(
    model_name=model_name,
    train_dataset=tokenized_dataset['train'],
    val_dataset=tokenized_dataset['validation']
)

QAtrainer.training()

# use_tpu = True  # Change to True if using TPU

# if use_tpu:
#     # Create distribution strategy
#     print('TPU used')
#     tpu = tf.distribute.cluster_resolver.TPUClusterResolver.connect()
#     strategy = tf.distribute.TPUStrategy(tpu)

#     with strategy.scope():
#         # Create model
#         print('TPU used')
# #         model = create_model(model_name)
#         # Create trainer
#         QAtrainer = QATrainer(
#             model_name=model_name,
#             train_dataset=tokenized_dataset['train'],
#             val_dataset=tokenized_dataset['validation']
#         )
# else:
#     if tf.config.list_physical_devices('GPU'):
# #         gpus = tf.config.experimental.list_physical_devices('GPU')
# #         for gpu in gpus:
# #             tf.config.experimental.set_virtual_device_configuration(
# #                 gpu, [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])
# #         tf.config.optimizer.set_jit(True)
# #         policy = tf.keras.mixed_precision.experimental.Policy('mixed_float16')
# #         tf.keras.mixed_precision.experimental.set_policy(policy)
#         strategy = tf.distribute.MirroredStrategy()
#     else:
#         strategy = tf.distribute.OneDeviceStrategy(device="/CPU:0")

#     with strategy.scope():
# #         model = create_model(model_name)
#         # Create trainer
#         QAtrainer = QATrainer(
#             model_name=model_name,
#             train_dataset=tokenized_dataset['train'],
#             val_dataset=tokenized_dataset['validation']
#         )

# # Train the model
# QAtrainer.training()



In [ ]:
len(tokenized_dataset['train']['attention_mask'][6])

In [ ]:
tokenized_datasets['validation']

In [ ]:
qa_dataset = QADataset(train_data, val_data)
qa_dataset.dataset_dict

In [ ]:
train_data[0]

In [ ]:
!pip list | grep transformers

In [ ]:
# загружаем данные для обучения
with open('/kaggle/input/nlp-test-task-2023/nlp_test_task_2023/dataset/train.json', 'r', encoding='utf-8') as file:
    train_data = json.load(file)

# загружаем данные для предсказания
with open('/kaggle/input/nlp-test-task-2023/nlp_test_task_2023/dataset/test.json', 'r', encoding='utf-8') as file:
    test_data = json.load(file)

# Разбиваем данные на обучающую и валидационную выборки
train_data, val_data = train_test_split(train_data, test_size=0.2, random_state=42)

In [ ]:
def create_dataframe(data, fields, subfields):
    main_df = pd.DataFrame(data)[fields]
    sub_df_list = []
    for subfield in subfields:
        sub_df = pd.DataFrame(list(main_df[subfield]))
        sub_df.columns = [f"{subfield}_{col}" for col in sub_df.columns]
        sub_df_list.append(sub_df)
    main_df = main_df.drop(columns=['extracted_part'])
    return pd.concat([main_df] + sub_df_list, axis=1)


In [ ]:
create_qa_examples(train_data)[0]['context']

In [ ]:

max_seq_length = 4000
model_name = "valhalla/longformer-base-4096-finetuned-squadv1"
# LongformerTokenizer.from_pretrained("valhalla/longformer-base-4096-finetuned-squadv1")
tokenizer = AutoTokenizer.from_pretrained(model_name)
config = LongformerConfig.from_pretrained('valhalla/longformer-base-4096-finetuned-squadv1')
config.attention_mode = 'sliding_chunks'

num_epochs = 3
batch_size = 16
pad_on_right = tokenizer.padding_side == "right"
train_dataset = QADataset(train_data, model_name, max_seq_length)
val_dataset = QADataset(val_data, model_name, max_seq_length)
# train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
# val_dataloader = DataLoader(val_dataset, batch_size=batch_size)
assert isinstance(tokenizer, transformers.PreTrainedTokenizerFast)


In [ ]:
train_dataset[0]

In [ ]:
tokenizer('<s>', '<s>')

In [ ]:
QAtrainer = QATrainer(
    model_name=model_name,
    train_dataset=tokenized_dataset['train'],
    val_dataset=tokenized_dataset['validation']
)

QAtrainer.training()

# TPU used try 2

In [ ]:
import tensorflow as tf
try:
    # TPU detection. No parameters necessary if TPU_NAME environment variable is
    # set: this is always the case on Kaggle.
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
    print('Running on TPU ', tpu.master())
except ValueError:
    tpu = None

if tpu:
    tf.config.experimental_connect_to_cluster(tpu)
    tf.tpu.experimental.initialize_tpu_system(tpu)
    strategy = tf.distribute.experimental.TPUStrategy(tpu)
else:
    # Default distribution strategy in Tensorflow. Works on CPU and single GPU.
    strategy = tf.distribute.get_strategy()

print("REPLICAS: ", strategy.num_replicas_in_sync)

In [ ]:
from transformers import default_data_collator
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AutoModelForQuestionAnswering.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
data_collator = default_data_collator
args = TrainingArguments(
    model_name,
    evaluation_strategy = "epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    push_to_hub=True,
)
trainer = Trainer(
    model,
    args,
    train_dataset=tokenized_dataset['train'],
    eval_dataset=tokenized_dataset['validation'],
    data_collator=data_collator,
    tokenizer=tokenizer,
)
trainer.train()

In [ ]:


from transformers import BertConfig, BertModel

# bert_config = BertConfig(
#     vocab_size=32000,
#     hidden_size=768,
#     num_hidden_layers=12,
#     num_attention_heads=12,
#     intermediate_size=3072,
#     hidden_dropout_prob=0.1,
#     attention_probs_dropout_prob=0.1,
#     max_position_embeddings=512,
#     type_vocab_size=2,
#     initializer_range=0.02,
#     layer_norm_eps=1e-12,
#     gradient_checkpointing=False,
#     position_embedding_type="absolute",
#     use_cache=True,
#     is_decoder=False,
#     pad_token_id=0,
#     bos_token_id=1,
#     eos_token_id=2
# )

tokenizer = AutoTokenizer.from_pretrained("valhalla/longformer-base-4096-finetuned-squadv1")
max_seq_length = 4000
batch_size = 16
epochs = eps = 1
     
train_dataset = QADataset(train_data, tokenizer, max_seq_length)
val_dataset = QADataset(val_data, tokenizer, max_seq_length)
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size)

# qa_model = QAModel(bert_config)
# qa_trainer = QATrainer(qa_model, train_dataloader, val_dataloader, lr=1e-12, eps=eps)
# train_losses, val_losses = qa_trainer.train(epochs)


In [ ]:
def evaluate(model, val_loader):
    model.eval()
    total_loss = 0
    with torch.no_grad():
        for step, batch in enumerate(val_loader):
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            segment_ids = batch['segment_ids'].to(device)
            start_positions = batch['start_positions'].to(device)
            end_positions = batch['end_positions'].to(device)
            outputs = model(input_ids, attention_mask=attention_mask, token_type_ids=segment_ids, start_positions=start_positions, end_positions=end_positions)
            loss = outputs.loss
            total_loss += loss.item()
        avg_loss = total_loss / len(val_loader)
        return avg_loss

def predict(model, test_loader):
    model.eval()
    predictions = []
    with torch.no_grad():
        for step, batch in enumerate(test_loader):
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            segment_ids = batch['segment_ids'].to(device)
            outputs = model(input_ids=input_ids, attention_mask=attention_mask, token_type_ids=segment_ids)
            start_logits, end_logits = outputs.start_logits, outputs.end_logits
            start_preds = torch.softmax(start_logits, dim=1).cpu().detach().numpy()
            end_preds = torch.softmax(end_logits, dim=1).cpu().detach().numpy()
            for i in range(len(start_preds)):
                start_pred = np.argmax(start_preds[i])
                end_pred = np.argmax(end_preds[i])
                if start_pred > end_pred:
                    answer = ""
                else:
                    answer = tokenizer.decode(input_ids[i][start_pred:end_pred+1], skip_special_tokens=True)
                predictions.append({
                    "context": batch['context'][i],
                    "question": batch['question'][i],
                    "extracted_part": answer
                })
    with open('predictions.json', 'w', encoding='utf-8') as f:
        json.dump(predictions, f, ensure_ascii=False, indent=4)


In [ ]:
class QADataset(Dataset):
    def __init__(self, data, tokenizer, max_seq_length):
        self.examples = self.create_qa_examples(data)
        self.tokenizer = tokenizer
        self.max_seq_length = max_seq_length
        self.skip = False

    def __len__(self):
        return len(self.examples)
    
    def __getitem__(self, idx):
        example = self.examples[idx]
        context = example['context']
        question = example['question']
        answer = example['answer']
        answer_start = example['answer_start']
        answer_end = example['answer_end']
        assert answer_end <= len(example['context'])
        is_char_in_ans = [0] * len(context)
        for i in range(answer_start, answer_end):
            is_char_in_ans[i] = 1
        tokenized_context = self.tokenizer.encode_plus(context, add_special_tokens=False, return_offsets_mapping=True, return_tensors="tf")
        ans_token_idx = []
        is_ans_token = [0] * len(tokenized_context)

        for idx, token in enumerate(tokenized_context):
            token_start = tokenized_context.token_to_chars(idx)[0]
            token_end = tokenized_context.token_to_chars(idx)[1]
            if sum(is_char_in_ans[token_start:token_end]) > 0:
                ans_token_idx.append(idx)
                for i in range(token_start, token_end):
                    is_ans_token[i] = 1
        if sum(is_ans_token) == 0:
            start_token_idx, end_token_idx = 0, 0
        else:
            start_token_idx = ans_token_idx[0]
            end_token_idx = ans_token_idx[-1]
            while start_token_idx > 0 and is_ans_token[tokenized_context.token_to_chars(start_token_idx-1)[0]]:
                start_token_idx -= 1
            while end_token_idx < len(tokenized_context)-1 and is_ans_token[tokenized_context.token_to_chars(end_token_idx+1)[1]-1]:
                end_token_idx += 1
            

        tokenized_question = self.tokenizer.encode_plus(question, return_offsets_mapping=True, return_tensors="tf")
        tokens = ['<s>'] + tokenized_context.tokens() + ['</s>']+ ['</s>'] + tokenized_question.tokens() + ['</s>']
        input_ids = self.tokenizer.convert_tokens_to_ids(tokens)
        token_type_ids = [0] * (len(tokenized_context.tokens())+2) + [1] * (len(
            tokenized_question.tokens())+2)
        attention_mask = [1] * len(input_ids)
        padding_length = self.max_seq_length - len(input_ids)
        if padding_length > 0:  # pad
            input_ids = input_ids + ([0] * padding_length)
            attention_mask = attention_mask + ([0] * padding_length)
            token_type_ids = token_type_ids + ([0] * padding_length)
        elif padding_length < 0:  # skip
            self.skip = True
            return
        features = []
#         encoded_dict = self.tokenizer.encode_plus(
#             question,
#             context,
#             add_special_tokens=True,
#             truncation='longest_first',
#             max_length=self.max_seq_length,
#             return_tensors='pt'
#         )
#         input_ids = encoded_dict['input_ids'].squeeze()
#         attention_mask = encoded_dict['attention_mask'].squeeze()
#         input_ids = torch.nn.functional.pad(encoded_dict['input_ids'], (0, self.max_seq_length - encoded_dict['input_ids'].shape[1]), mode='constant', value=0)
#         attention_mask = torch.nn.functional.pad(encoded_dict['attention_mask'], (0, self.max_seq_length - encoded_dict['attention_mask'].shape[1]), mode='constant', value=0)
        
        features = {'input_ids': input_ids, 'attention_mask': attention_mask, 
                    'token_type_ids': token_type_ids, 'start_token_idx': start_token_idx, 'end_token_idx': end_token_idx}
#         max_len_dict = {}
#         for key, value in features.items():
#             if isinstance(value, (list, tuple)):
#                 max_len_dict[key] = max(len(seq) for seq in value)
#         for key, value in features.items():
#             if isinstance(value, (list, tuple)):
#                 max_len = max_len_dict[key]
#                 for i in range(len(value)):
#                     pad_len = max_len - len(value[i])
#                     value[i] = torch.cat([value[i], torch.zeros(pad_len, dtype=torch.long)])
#                 features[key] = torch.stack(value)

        return features
    
    def create_qa_examples(self, data):
        examples = []
        for row in data:
            text = row['text']
            question = row['label']
            extracted_part = row.get('extracted_part', {})
            if extracted_part and 'text' in extracted_part:
                answer = extracted_part['text'][0].strip()
                answer_start = extracted_part['answer_start'][0]
                answer_end = extracted_part['answer_end'][0]
            else:
                answer = answer_start = answer_end = None

            example = {'context': text, 'question': question, 'answer': answer, 'answer_start': answer_start, 'answer_end': answer_end}
            examples.append(example)
        return examples
    
    
    @staticmethod
    def prepare_test_data(data):
        examples = []
        for row in data:
            text = row['text']
            question = row['label']
            example = {'context': text, 'question': question}
            examples.append(example)
        return examples

def collate_fn(batch, device):
    input_ids = pad_sequence([torch.tensor(example['input_ids']) for example in batch], batch_first=True, padding_value=0).to(device)
    attention_mask = pad_sequence([torch.tensor(example['attention_mask']) for example in batch], batch_first=True, padding_value=0).to(device)
    token_type_ids = pad_sequence([torch.tensor(example['token_type_ids']) for example in batch], batch_first=True, padding_value=0).to(device)
    start_positions = torch.tensor([example['answer_start'] for example in batch]).to(device)
    end_positions = torch.tensor([example['answer_end'] for example in batch]).to(device)
    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'token_type_ids': token_type_ids,
        'start_positions': start_positions,
        'end_positions': end_positions
    }


def create_inputs_targets(dataset):
    dataset_dict = {
        "input_ids": [],
        "token_type_ids": [],
        "attention_mask": [],
        "start_token_idx": [],
        "end_token_idx": [],
    }
    for idx in range(len(dataset)):
        example = dataset[idx]
        for key in dataset_dict:
            if isinstance(example[key], torch.Tensor):
                value = example[key].numpy().tolist()
            else:
                value = example[key]
            dataset_dict[key].append(value)


    x = [
        dataset_dict["input_ids"],
        dataset_dict["token_type_ids"],
        dataset_dict["attention_mask"],
    ]
    y = [dataset_dict["start_token_idx"], dataset_dict["end_token_idx"]]
    return x, y

def x_y_split(model_name, train_data, validation_data, batch_size):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = TFAutoModelForQuestionAnswering.from_pretrained(model_name)
#     device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    train_dataset = QADataset(train_data, tokenizer, max_seq_length)
#     train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, drop_last=True,
#                                    collate_fn=lambda batch: collate_fn(batch, device))
    x_train, y_train = create_inputs_targets(train_dataset)
    
    validation_dataset = QADataset(validation_data, tokenizer, max_seq_length)
#     validation_dataloader = DataLoader(validation_dataset, batch_size=batch_size, shuffle=False, drop_last=True,
#                                         collate_fn=lambda batch: collate_fn(batch, device))
    x_val, y_val = create_inputs_targets(validation_dataset)

    return x_train, y_train, x_val, y_val



def create_model(model_name):
    ## BERT encoder
    encoder = TFLongformerForQuestionAnswering.from_pretrained(model_name)

    ## QA Model
    input_ids = layers.Input(shape=(max_len,), dtype=tf.int32)
    token_type_ids = layers.Input(shape=(max_len,), dtype=tf.int32)
    attention_mask = layers.Input(shape=(max_len,), dtype=tf.int32)
    embedding = encoder(
        input_ids, token_type_ids=token_type_ids, attention_mask=attention_mask
    )[0]

    start_logits = layers.Dense(1, name="start_logit", use_bias=False)(embedding)
    start_logits = layers.Flatten()(start_logits)

    end_logits = layers.Dense(1, name="end_logit", use_bias=False)(embedding)
    end_logits = layers.Flatten()(end_logits)

    start_probs = layers.Activation(keras.activations.softmax)(start_logits)
    end_probs = layers.Activation(keras.activations.softmax)(end_logits)

    model = keras.Model(
        inputs=[input_ids, token_type_ids, attention_mask],
        outputs=[start_probs, end_probs],
    )
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=False)
    optimizer = keras.optimizers.Adam(lr=5e-5)
    model.compile(optimizer=optimizer, loss=[loss, loss])
    return model

class ExactMatch(keras.callbacks.Callback):
    def __init__(self, x_eval, y_eval):
        super().__init__()
        self.x_eval = x_eval
        self.y_eval = y_eval

    def on_epoch_end(self, epoch, logs=None):
        pred_start, pred_end = self.model.predict(self.x_eval)
        count = 0
        for idx, (start, end) in enumerate(zip(pred_start, pred_end)):
            offsets = squad_eg.context_token_to_char
            start = np.argmax(start)
            end = np.argmax(end)
            if start >= len(offsets):
                continue
            pred_char_start = offsets[start][0]
            if end < len(offsets):
                pred_char_end = offsets[end][1]
                pred_ans = squad_eg.context[pred_char_start:pred_char_end]
            else:
                pred_ans = squad_eg.context[pred_char_start:]

            if pred_ans in squad_eg.all_answers:
                count += 1
        acc = count / len(self.y_eval[0])
        print(f"\nepoch={epoch+1}, exact match score={acc:.2f}")


In [ ]:
tokenizer = AutoTokenizer.from_pretrained("valhalla/longformer-base-4096-finetuned-squadv1")
examp = QADataset(train_data, tokenizer, max_seq_length)

In [ ]:
QADataset(train_data, tokenizer, max_seq_length)

In [ ]:
# загружаем данные для обучения
with open('/kaggle/input/nlp-test-task-2023/nlp_test_task_2023/dataset/train.json', 'r', encoding='utf-8') as file:
    train_data = json.load(file)

# загружаем данные для предсказания
with open('/kaggle/input/nlp-test-task-2023/nlp_test_task_2023/dataset/test.json', 'r', encoding='utf-8') as file:
    test_data = json.load(file)

# Разбиваем данные на обучающую и валидационную выборки
train_data, validation_data = train_test_split(train_data[:50], test_size=0.2, random_state=42)
max_seq_length = 4000
model_name = "valhalla/longformer-base-4096-finetuned-squadv1"
configuration = LongformerConfig()
num_epochs = 3

x_train, y_train, x_val, y_val = x_y_split(model_name = model_name, train_data = train_data, validation_data = validation_data, batch_size = 16)
max_len = len(x_train[0][0])

In [ ]:
len(y_train[0])

In [ ]:
x_train имеет структуру словаря, в котором есть 3 подсловаря - признака, в каждом из них набор примеров n-го количества, в каждом примере уже непосредственно находятся данные
в y_train 2 словаря, которые содержат n примеров, в каждом из которых находится таргет. 
какие модели обучения можно написать на таких данных, не пользуясь предобученными моделями и их ограничениями

In [ ]:

tf.debugging.set_log_device_placement(True)

In [ ]:
tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(log_device_placement=True))

In [ ]:
use_tpu = False  # Change to True if using TPU

if use_tpu:
    # Create distribution strategy
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver.connect()
    strategy = tf.distribute.TPUStrategy(tpu)

    # Create model
    with strategy.scope():
        print('TPU used')
        model = create_model(model_name)
else:
#     # Use GPU if TPU is not available
#     if tf.config.list_physical_devices('GPU'):
#         strategy = tf.distribute.MirroredStrategy()
        
#     else:
    strategy = tf.distribute.OneDeviceStrategy(device="/CPU:0")

    with strategy.scope():
        model = create_model(model_name)

model.summary()


In [ ]:
import tensorflow as tf
print(tf.__version__)
print(tf.test.is_built_with_cuda())
print(tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None))


In [ ]:

x_train_np = [np.array(x_train[0]), np.array(x_train[1]), np.array(x_train[2])]
y_train_np = [np.array(y_train[0]), np.array(y_train[1])]
x_val_np = [np.array(x_val[0]), np.array(x_val[1]), np.array(x_val[2])]
y_val_np = [np.array(y_val[0]), np.array(y_val[1])]
exact_match_callback = ExactMatch(x_val_np, y_val_np)
model.fit(
    x_train_np,
    y_train_np,
    validation_data=(x_val_np, y_val_np),
    epochs=1,
    verbose=2,
    batch_size=64,
#     callbacks=[exact_match_callback],
)


In [ ]:
train_dataset = QADataset(train_data, tokenizer, max_seq_length)
train_dataloader = DataLoader(train_dataset, batch_size=16, shuffle=True, drop_last=True,
                               collate_fn=lambda batch: collate_fn(batch, device))

In [ ]:
train_dataloader.dataset[2]

In [ ]:
# tokenizer = AutoTokenizer.from_pretrained('cointegrated/LaBSE-en-ru')
# examples = QADataset.create_qa_examples(train_data, train_data)
# questions = [example['context'] for example in examples]
# question_tokens = [tokenizer.tokenize(question) for question in questions]
# import matplotlib.pyplot as plt

# question_lengths = [len(tokens) for tokens in question_tokens]
# plt.hist(question_lengths, bins=50)
# plt.xlabel('Length of question tokens')
# plt.ylabel('Frequency')
# plt.show()

In [ ]:
# # Разбиваем данные на обучающую и валидационную выборки
# train_data, validation_data = train_test_split(train_data, test_size=0.2, random_state=42)
# max_seq_length = 3072
# model_name = "allenai/longformer-large-4096-finetuned-triviaqa"

# # Число эпох обучения
# num_epochs = 3
# output_dir = 'my_model'

In [ ]:
# 'cointegrated/LaBSE-en-ru'


In [ ]:
# from transformers import BigBirdTokenizer, BigBirdForQuestionAnswering

# tokenizer = BigBirdTokenizer.from_pretrained('google/bigbird-roberta-base')
# model = BigBirdForQuestionAnswering.from_pretrained('google/bigbird-roberta-base')


In [ ]:

# import tensorflow as tf

# train(model_name, train_data, validation_data, output_dir)